In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("cities.csv")

In [4]:
df.to_html('cities.html')

,Unnamed: 0,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,0,Ushuaia,-54.8000,-68.3000,38.82,64,20,6.91,AR,1658868434
1,1,Arraial do Cabo,-22.9661,-42.0278,73.36,78,0,14.97,BR,1658868253
2,2,Orlik,52.5178,99.8250,42.64,84,68,0.72,RU,1658868434
3,3,Mataura,-46.1927,168.8643,44.47,97,100,7.02,NZ,1658868435
4,4,Chapada dos Guimarães,-15.4606,-55.7497,87.46,22,5,2.98,BR,1658868435
...,...,...,...,...,...,...,...,...,...,...
541,541,Semporna,4.4818,118.6112,78.57,84,100,2.89,MY,1658868646
542,542,Magaria,12.9983,8.9099,86.07,59,100,18.41,NE,1658868646
543,543,Ciudad Real,39.0000,-4.0000,88.14,24,0,5.99,ES,1658868646
544,544,Maniitsoq,65.4167,-52.9000,40.71,92,85,9.46,GL,1658868647
545,545,Vila Franca do Campo,37.7167,-25.4333,78.19,89,39,5.59,PT,1658868647